### ISSUE TITLE
Anteproyecto 

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-3#2]
[anteproyecto .pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-anteproyecto-equipo-3/files/9701021/anteproyecto.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tienen un 18 de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
